// id toko sesuai yaa sama di shop.js
// 101: Rosy Garden
// 102: Eternal Florist
// 103: The Flower Studio
// 104: Sentra Bunga
// 105: Luxe De Pere
// 106: Petal & Paper

export const MOCK_PACKAGINGS = [
  { 
    id: "p-101-1",
    shop_id: 101,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-101-2",
    shop_id: 101,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-101-3",
    shop_id: 101,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-101-4",
    shop_id: 101,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-101-5",
    shop_id: 101,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-101-6",
    shop_id: 101,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  
  { 
    id: "p-102-1",
    shop_id: 102,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-102-2",
    shop_id: 102,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-102-3",
    shop_id: 102,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-102-4",
    shop_id: 102,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-102-5",
    shop_id: 102,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-102-6",
    shop_id: 102,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },

  { 
    id: "p-103-1",
    shop_id: 103,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-103-2",
    shop_id: 103,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-103-3",
    shop_id: 103,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-103-4",
    shop_id: 103,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-103-5",
    shop_id: 103,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-103-6",
    shop_id: 103,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-104-1",
    shop_id: 104,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-104-2",
    shop_id: 104,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-104-3",
    shop_id: 104,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-104-4",
    shop_id: 104,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-104-5",
    shop_id: 104,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-104-6",
    shop_id: 104,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-105-1",
    shop_id: 105,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-105-2",
    shop_id: 105,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-105-3",
    shop_id: 105,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-105-4",
    shop_id: 105,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-105-5",
    shop_id: 105,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-105-6",
    shop_id: 105,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-106-1",
    shop_id: 106,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-106-2",
    shop_id: 106,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-106-3",
    shop_id: 106,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-106-4",
    shop_id: 106,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-106-5",
    shop_id: 106,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-106-6",
    shop_id: 106,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-107-1",
    shop_id: 107,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-107-2",
    shop_id: 107,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-107-3",
    shop_id: 107,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-107-4",
    shop_id: 107,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-107-5",
    shop_id: 107,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-107-6",
    shop_id: 107,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-108-1",
    shop_id: 108,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-108-2",
    shop_id: 108,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-108-3",
    shop_id: 108,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-108-4",
    shop_id: 108,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-108-5",
    shop_id: 108,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-108-6",
    shop_id: 108,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-109-1",
    shop_id: 109,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-109-2",
    shop_id: 109,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-109-3",
    shop_id: 109,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-109-4",
    shop_id: 109,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-109-5",
    shop_id: 109,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-109-6",
    shop_id: 109,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-110-1",
    shop_id: 110,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-110-2",
    shop_id: 110,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-110-3",
    shop_id: 110,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-110-4",
    shop_id: 110,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-110-5",
    shop_id: 110,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-110-6",
    shop_id: 110,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-111-1",
    shop_id: 111,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-111-2",
    shop_id: 111,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-111-3",
    shop_id: 111,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-111-4",
    shop_id: 111,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-111-5",
    shop_id: 111,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-111-6",
    shop_id: 111,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  { 
    id: "p-112-1",
    shop_id: 112,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-112-2",
    shop_id: 112,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-112-3",
    shop_id: 112,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },
  {
    id: "p-112-4",
    shop_id: 112,
    type: "wrapping",
    name: "Premium Paper Wrap",
    price: 15000,
    variants: [
      { name: "Pastel Pink", hex: "#FFD1DC", stock: 20 },
      { name: "Sage Green", hex: "#A3B18A", stock: 15 },
      { name: "Cream Ivory", hex: "#FFFFF0", stock: 50 },
      { name: "Black Elegant", hex: "#2C2C2C", stock: 10 },
      { name: "Lilac", hex: "#C8A2C8", stock: 5 },
    ],
  },
  {
    id: "p-112-5",
    shop_id: 112,
    type: "box",
    name: "Bloom Box Round",
    price: 35000,
    variants: [
      { name: "White Box", hex: "#FFFFFF", stock: 10 },
      { name: "Pink Box", hex: "#FFC0CB", stock: 5 },
      { name: "Black Box", hex: "#000000", stock: 8 },
    ],
  },
  {
    id: "p-112-6",
    shop_id: 112,
    type: "ribbon",
    name: "Satin Ribbon Only",
    price: 5000,
    variants: [{ name: "Red Ribbon", hex: "#FFFFFF", stock: 100 }],
  },

];

export const FLOWER_LIBRARY = [
  // --- ROMANCE COLLECTION ---
  {
    id: "r1",
    shop_id: 101, // Rosy Garden (Specialist Mawar)
    name: "Red Rose",
    category: "romance",
    price: 13000,
    image: "/assets/romance/red_rose.png",
    color: "bg-red-500",
  },
  {
    id: "r2",
    shop_id: 101, // Rosy Garden
    name: "Peony Pink",
    category: "romance",
    price: 40000,
    image: "/assets/romance/peony.png",
    color: "bg-pink-400",
  },
  {
    id: "r3",
    shop_id: 104, // Sentra Bunga (Market - Tulip biasanya banyak disini)
    name: "Red Tulip",
    category: "romance",
    price: 19000,
    image: "/assets/romance/red_tulip.png",
    color: "bg-red-600",
  },
  {
    id: "r4",
    shop_id: 103, // The Flower Studio (Artistic)
    name: "Calla Lily",
    category: "romance",
    price: 17000,
    image: "/assets/romance/calla_lily.png",
    color: "bg-red-500",
  },
  {
    id: "r5",
    shop_id: 101, // Rosy Garden
    name: "Deep Pink Rose",
    category: "romance",
    price: 40000,
    image: "/assets/romance/deep_pink_rose.png",
    color: "bg-pink-400",
  },
  {
    id: "r6",
    shop_id: 105, // Luxe (Premium Orchid)
    name: "Pink Orchid",
    category: "romance",
    price: 19000,
    image: "/assets/romance/pink_orchid.png",
    color: "bg-red-600",
  },

  {
    id: "r7",
    shop_id: 102,
    name: "Red Rose",
    category: "romance",
    price: 18000,
    image: "/assets/romance/red_rose.png",
    color: "bg-red-500",
  },
  {
    id: "r8",
    shop_id: 106, // Petal & Paper
    name: "Peony Pink",
    category: "romance",
    price: 38000,
    image: "/assets/romance/peony.png",
    color: "bg-pink-400",
  },
  {
    id: "r9",
    shop_id: 107, // Flower Studio
    name: "Red Tulip",
    category: "romance",
    price: 19000,
    image: "/assets/romance/red_tulip.png",
    color: "bg-red-600",
  },
  {
    id: "r10",
    shop_id: 103, // Flower Studio
    name: "Red Ranunculus",
    category: "romance",
    price: 55000,
    image: "/assets/romance/red_ranunculus.png",
    color: "bg-red-600",
  },
  {
    id: "r11",
    shop_id: 101, // Rosy Garden
    name: "Spray Rose",
    category: "romance",
    price: 30000,
    image: "/assets/romance/spray_rose.png",
    color: "bg-red-600",
  },
  {
    id: "r12",
    shop_id: 109, // Flower Studio
    name: "Seeded Eucalyptus",
    category: "romance",
    price: 3000,
    image: "/assets/romance/seeded_eucalyptus.png",
    color: "bg-red-600",
  },
  {
    id: "r13",
    shop_id: 108, // Flower Studio
    name: "Ruscus",
    category: "romance",
    price: 25000,
    image: "/assets/romance/ruscus.png",
    color: "bg-red-600",
  },

  // --- GRATITUDE COLLECTION ---
  {
    id: "g1",
    shop_id: 102, // Eternal Florist
    name: "Sunflower",
    category: "gratitude",
    price: 45000,
    image: "/assets/gratitude/sunflower.png",
    color: "bg-yellow-400",
  },
  {
    id: "g2",
    shop_id: 105, // Luxe (White Orchid Premium)
    name: "White Orchid",
    category: "gratitude",
    price: 150000,
    image: "/assets/gratitude/white_orchid.png",
    color: "bg-white",
  },
  {
    id: "g3",
    shop_id: 103, // Flower Studio (Suka pakai filler unik)
    name: "Eucalyptus",
    category: "gratitude",
    price: 35000,
    image: "/assets/gratitude/eucalyptus.png",
    color: "bg-green-700",
  },
  {
    id: "g4",
    shop_id: 105, // Luxe (White Orchid Premium)
    name: "Cyan Hydrangea",
    category: "gratitude",
    price: 30000,
    image: "/assets/gratitude/cyan_hydrangea.png",
    color: "bg-white",
  },
  {
    id: "g5",
    shop_id: 111, // Luxe (White Orchid Premium)
    name: "Gerbera",
    category: "gratitude",
    price: 30000,
    image: "/assets/gratitude/gerbera.png",
    color: "bg-white",
  },
  {
    id: "g6",
    shop_id: 104,
    name: "White Carnation",
    category: "gratitude",
    price: 21000,
    image: "/assets/gratitude/white_carnation.png",
    color: "bg-white",
  },
  {
    id: "g7",
    shop_id: 105,
    name: "White Lisianthus",
    category: "gratitude",
    price: 30000,
    image: "/assets/gratitude/white_lisianthus.png",
    color: "bg-white",
  },
  {
    id: "g8",
    shop_id: 112,
    name: "White Rose",
    category: "gratitude",
    price: 17000,
    image: "/assets/gratitude/white_rose.png",
    color: "bg-white",
  },
  {
    id: "g9",
    shop_id: 104,
    name: "Yellow Rose",
    category: "gratitude",
    price: 17000,
    image: "/assets/gratitude/yellow_rose.png",
    color: "bg-yellow-300",
  },
  {
    id: "g10",
    shop_id: 111,
    name: "Yellow Tulip",
    category: "gratitude",
    price: 19000,
    image: "/assets/gratitude/yellow_tulip.png",
    color: "bg-yellow-300",
  },

  // --- REGRET COLLECTION ---
  {
    id: "rg1",
    shop_id: 104, // Sentra Bunga (Grosir Filler)
    name: "Baby's Breath",
    category: "regret",
    price: 40000,
    unit: "per 1 ikat besar",
    image: "/assets/regret/babys_breathe.png",
    color: "bg-gray-100",
  },
  {
    id: "rg2",
    shop_id: 112, // Flower Studio
    name: "Blue Hydrangea",
    category: "regret",
    price: 75000,
    image: "/assets/regret/blue_hydrangea.png",
    color: "bg-blue-300",
  },
  {
    id: "rg3",
    shop_id: 112, // Luxe (Mawar Hitam Langka)
    name: "Black Rose",
    category: "regret",
    price: 30000,
    image: "/assets/regret/black_rose.png",
    color: "bg-gray-900",
  },
  {
    id: "rg4",
    shop_id: 104, // Sentra Bunga (filler grosir)
    name: "Baby's Breath",
    category: "regret",
    price: 40000,
    image: "/assets/regret/babys_breathe.png",
    color: "bg-gray-100",
  },
  {
    id: "rg5",
    shop_id: 105, // Luxe (dyed flower)
    name: "Black Rose",
    category: "regret",
    price: 40000,
    image: "/assets/regret/black_rose.png",
    color: "bg-gray-900",
  },
  {
    id: "rg6",
    shop_id: 103,
    name: "Blue Hydrangea",
    category: "regret",
    price: 90000,
    image: "/assets/regret/blue_hydrangea.png",
    color: "bg-blue-300",
  },
  {
    id: "rg7",
    shop_id: 101, // Rosy Garden
    name: "Dark Red Rose",
    category: "regret",
    price: 19000,
    image: "/assets/regret/dark_red_rose.png",
    color: "bg-red-800",
  },
  {
    id: "rg8",
    shop_id: 103,
    name: "Eucalyptus",
    category: "regret",
    price: 35000,
    image: "/assets/regret/eucalyptus.png",
    color: "bg-gray-600",
  },
  {
    id: "rg9",
    shop_id: 105,
    name: "Freesia",
    category: "regret",
    price: 240000,
    image: "/assets/regret/freesia.png",
    color: "bg-purple-200",
  },
  {
    id: "rg10",
    shop_id: 105,
    name: "Purple Lisianthus",
    category: "regret",
    price: 30000,
    image: "/assets/regret/purple_lisianthus.png",
    color: "bg-purple-400",
  },
  {
    id: "rg11",
    shop_id: 101,
    name: "Pink Rose",
    category: "regret",
    price: 17000,
    image: "/assets/regret/rose_pink.png",
    color: "bg-pink-300",
  },
  {
    id: "rg12",
    shop_id: 104,
    name: "White Carnation",
    category: "regret",
    price: 21000,
    image: "/assets/regret/white_carnation.png",
    color: "bg-gray-100",
  },
  {
    id: "rg13",
    shop_id: 104,
    name: "White Tulip",
    category: "regret",
    price: 18000,
    image: "/assets/regret/white_tulip.png",
    color: "bg-gray-100",
  },

  // --- grief COLLECTION ---
  {
    id: "p1",
    shop_id: 106, // Petal & Paper
    name: "Moonlight Serenity",
    category: "grief",
    price: 13000,
    image: "/assets/bouquet/grief/moonlight_serenity.png",
    color: "bg-purple-200",
  },
  {
    id: "p2",
    shop_id: 104,
    name: "Baby's Breathe",
    category: "grief",
    price: 40000,
    image: "/assets/grief/babys_breathe.png",
    color: "bg-gray-100",
  },
  {
    id: "p3",
    shop_id: 108,
    name: "Chamomile",
    category: "grief",
    price: 25000,
    image: "/assets/grief/chamomile.png",
    color: "bg-yellow-100",
  },
  {
    id: "p4",
    shop_id: 105,
    name: "Cyan Hydrangea",
    category: "grief",
    price: 30000,
    image: "/assets/grief/cyan_hydrangea.png",
    color: "bg-blue-200",
  },
  {
    id: "p5",
    shop_id: 103,
    name: "Eucalyptus",
    category: "grief",
    price: 35000,
    image: "/assets/grief/eucalyptus.png",
    color: "bg-green-700",
  },
  {
    id: "p6",
    shop_id: 106,
    name: "Lavender",
    category: "grief",
    price: 18000,
    image: "/assets/grief/lavender.png",
    color: "bg-purple-300",
  },
  {
    id: "p7",
    shop_id: 105,
    name: "Purple Orchid",
    category: "grief",
    price: 30000,
    image: "/assets/grief/purple_orchid.png",
    color: "bg-purple-600",
  },
  {
    id: "p8",
    shop_id: 109,
    name: "Ranunculus",
    category: "grief",
    price: 55000,
    image: "/assets/grief/ranunculus.png",
    color: "bg-pink-200",
  },
  {
    id: "p9",
    shop_id: 102,
    name: "White Lily",
    category: "grief",
    price: 27000,
    image: "/assets/grief/white_lily.png",
    color: "bg-white",
  },
  {
    id: "p10",
    shop_id: 105,
    name: "White Lisianthus",
    category: "grief",
    price: 30000,
    image: "/assets/grief/white_lisianthus.png",
    color: "bg-white",
  },
  {
    id: "p11",
    shop_id: 101,
    name: "White Rose",
    category: "grief",
    price: 17000,
    image: "/assets/grief/white_rose.png",
    color: "bg-white",
  },
  {
    id: "p12",
    shop_id: 112,
    name: "White Tulip",
    category: "grief",
    price: 18000,
    image: "/assets/grief/white_tulip.png",
    color: "bg-white",
  },
];
