export const FLOWER_LIBRARY = [
  // ROMANCE
  {
    id: "r1",
    name: "Red Rose",
    category: "romance",
    price: 85000,
    unit: "per 5 tangkai",
    image: "/assets/romance/red_rose.png",
    color: "bg-red-500",
  },
  {
    id: "r2",
    name: "Peony Pink",
    category: "romance",
    price: 120000,
    unit: "per 3 tangkai",
    image: "/assets/romance/peony.png",
    color: "bg-pink-400",
  },
  {
    id: "r3",
    name: "Red Tulip",
    category: "romance",
    price: 95000,
    unit: "per 5 tangkai",
    image: "/assets/romance/red_tulip.png",
    color: "bg-red-600",
  },
  {
    id: "r4",
    name: "Calla Lily",
    category: "romance",
    price: 85000,
    unit: "per 5 tangkai",
    image: "/assets/romance/calla_lily.png",
    color: "bg-red-500",
  },
  {
    id: "r5",
    name: "Deep Pink Rose",
    category: "romance",
    price: 120000,
    unit: "per 3 tangkai",
    image: "/assets/romance/deep_pink_rose.png",
    color: "bg-pink-400",
  },
  {
    id: "r6",
    name: "Pink Orchid",
    category: "romance",
    price: 95000,
    unit: "per 5 tangkai",
    image: "/assets/romance/pink_orchid.png",
    color: "bg-red-600",
  },
  {
    id: "r7",
    name: "Red Rose",
    category: "romance",
    price: 85000,
    unit: "per 5 tangkai",
    image: "/assets/romance/red_rose.png",
    color: "bg-red-500",
  },
  {
    id: "r8",
    name: "Peony Pink",
    category: "romance",
    price: 120000,
    unit: "per 3 tangkai",
    image: "/assets/romance/peony.png",
    color: "bg-pink-400",
  },
  {
    id: "r9",
    name: "Red Tulip",
    category: "romance",
    price: 95000,
    unit: "per 5 tangkai",
    image: "/assets/romance/red_tulip.png",
    color: "bg-red-600",
  },
  // GRATITUDE
  {
    id: "g1",
    name: "Sunflower",
    category: "gratitude",
    price: 45000,
    unit: "per 1 tangkai besar",
    image: "/assets/gratitude/sunflower.png",
    color: "bg-yellow-400",
  },
  {
    id: "g2",
    name: "White Orchid",
    category: "gratitude",
    price: 150000,
    unit: "per potong",
    image: "/assets/gratitude/white_orchid.png",
    color: "bg-white",
  },
  {
    id: "g3",
    name: "Eucalyptus",
    category: "gratitude",
    price: 35000,
    unit: "per 1 ikat",
    image: "/assets/gratitude/eucalyptus.png",
    color: "bg-green-700",
  },
  // REGRET
  {
    id: "rg1",
    name: "Baby's Breath",
    category: "regret",
    price: 40000,
    unit: "per 1 ikat besar",
    image: "/assets/regret/babys_breathe.png",
    color: "bg-gray-100",
  },
  {
    id: "rg2",
    name: "Blue Hydrangea",
    category: "regret",
    price: 75000,
    unit: "per 1 tangkai",
    image: "/assets/regret/blue_hydrangea.png",
    color: "bg-blue-300",
  },
  {
    id: "rg3",
    name: "Black Rose",
    category: "regret",
    price: 90000,
    unit: "per 3 tangkai",
    image: "/assets/regret/black_rose.png",
    color: "bg-gray-900",
  },
  // PEACE
  {
    id: "p1",
    name: "Moonlight Serenity",
    category: "peace",
    price: 65000,
    unit: "per 5 tangkai",
    image: "/assets/bouquet/peace/moonlight_serenity.png",
    color: "bg-purple-200",
  },
];
