// DATA TOKO (TENANTS)
export const SHOPS = [
  {
    id: 101,
    name: "Rosy Garden Bandung",
    location: "Dago, Bandung",
    image: "/assets/flowershop/rosy_garden.png",
    rating: 4.9,
    reviewCount: 1240,
    distance: "1.2 km",
    can_customize: true,
    openTime: "08.00 - 20.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 102,
    name: "Eternal Florist Jakarta",
    location: "Kemang, Jakarta Selatan",
    image: "/assets/flowershop/eternal_florist.png",
    rating: 4.7,
    reviewCount: 850,
    distance: "3.5 km",
    can_customize: false,
    openTime: "09.00 - 21.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 103,
    name: "The Flower Studio",
    location: "Cikini, Jakarta Pusat",
    image: "/assets/flowershop/the_flower_studio.png",
    rating: 4.8,
    reviewCount: 210,
    distance: "0.8 km",
    can_customize: true,
    openTime: "10.00 - 18.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 104,
    name: "Sentra Bunga Rawabelong",
    location: "Kebon Jeruk, Jakarta Barat",
    image: "/assets/flowershop/sentara_bunga.png",
    rating: 4.5,
    reviewCount: 5300,
    distance: "12 km",
    can_customize: false,
    openTime: "24 Jam",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 105,
    name: "Luxe De Pere En Fils",
    location: "SCBD, Jakarta Selatan",
    image: "/assets/flowershop/de_pere.png",
    rating: 5.0,
    reviewCount: 45,
    distance: "4.2 km",
    can_customize: true,
    openTime: "09.00 - 17.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 106,
    name: "Petal & Paper",
    location: "BSD City, Tangerang",
    image: "/assets/flowershop/petal_paper.png",
    rating: 4.6,
    reviewCount: 112,
    distance: "25 km",
    can_customize: true,
    openTime: "08.00 - 20.00",
    lat: -6.8869, lng: 107.6153,
  },
];

// DATA PRODUK (allItems)
export const allItems = [
  {
    id: 1,
    shop: SHOPS[0],
    type: "bouquet",
    title: "Head Over Heels",
    price: 850000,
    image: "/assets/bouquet/peace/crimson_promise.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    isBestSeller: true,
    desc: "Cinta yang meledak-ledak dan penuh afeksi. Cocok untuk menyatakan perasaan yang mendalam.",
    story:
      "Terinspirasi dari kisah cinta klasik yang tak lekang oleh waktu. Merah melambangkan keberanian mencintai.",
    care: "Potong ujung batang 1cm setiap hari, ganti air dingin, dan jauhkan dari sinar matahari langsung.",
    flowers: [
      "Mawar Merah (Red Rose) - 10 tangkai",
      "Baby Breath - Filler",
      "Daun Ruscus - Greenery",
      "Pita Satin Premium Maroon",
    ],
  },
  {
    id: 2,
    shop: SHOPS[0],
    type: "bouquet",
    title: "Sunset Harmony",
    price: 450000,
    image: "/assets/bouquet/peace/sunset_harmony.png",
    category: "Peace",
    tag: "Friendship",
    theme: "light",
    isBestSeller: false,
    desc: "Kesegaran pagi hari yang membawa ketenangan.",
    story:
      "Diciptakan untuk menyapa teman lama dengan kehangatan yang tidak berlebihan.",
    care: "Semprotkan air (mist) ke kelopak bunga tulip agar tetap segar.",
    flowers: [
      "White Tulip - 5 tangkai",
      "Lily of the Valley - 3 tangkai",
      "Transparent Wrapping",
    ],
  },
  {
    id: 3,
    shop: SHOPS[0],
    type: "bouquet",
    title: "Bright Future",
    price: 450000,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Menyambut masa depan cerah dengan penuh optimisme.",
    story:
      "Bouquet ini melambangkan harapan dan langkah baru menuju masa depan.",
    care: "Ganti air setiap dua hari.",
    flowers: ["Yellow Tulip", "Gerbera", "Eucalyptus"],
  },
  {
    id: 4,
    shop: SHOPS[5],
    type: "bouquet",
    title: "Sweet Gratitude",
    price: 350000,
    image: "/assets/bouquet/peace/moonlight_serenity.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: true,
    desc: "Ucapan terima kasih yang sederhana namun tulus.",
    story:
      "Diciptakan untuk mengungkapkan rasa terima kasih tanpa kata-kata berlebihan.",
    care: "Letakkan di ruangan sejuk.",
    flowers: ["White Rose", "Lisianthus", "Soft Wrapping"],
  },
  {
    id: 5,
    shop: SHOPS[1],
    type: "bouquet",
    title: "Silent Tears",
    price: 700000,
    image: "/assets/bouquet/regret/sweet_apology.png",
    category: "Gloomy",
    tag: "Grief",
    theme: "dark",
    isBestSeller: false,
    desc: "Penghormatan terakhir dengan ketulusan dan kedamaian.",
    story: "Melambangkan kesedihan yang hening namun penuh penghormatan.",
    care: "Jauhkan dari panas dan sinar matahari.",
    flowers: ["Dark Red Rose", "White Lily", "Ruscus"],
  },
  { id: "promo-1", type: "promo" },
  {
    id: 6,
    shop: SHOPS[2],
    type: "bouquet",
    title: "Midnight Regret",
    price: 480000,
    image: "/assets/bouquet/regret/first_date_bloom.png",
    category: "Gloomy",
    tag: "Regret",
    theme: "dark",
    isBestSeller: true,
    desc: "Penyesalan yang dalam dan sunyi.",
    story: "Terinspirasi dari perasaan yang datang terlambat di tengah malam.",
    care: "Ganti air setiap hari.",
    flowers: ["White Rose", "Freesia", "Purple Lisianthus"],
  },
  {
    id: 7,
    shop: SHOPS[3],
    type: "bouquet",
    title: "Garden Symphony",
    price: 820000,
    image: "/assets/bouquet/romance/garden_syphony.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Harmoni cinta yang tumbuh alami.",
    story: "Seperti taman yang mekar perlahan, cinta pun tumbuh dengan lembut.",
    care: "Potong batang 1-2cm setiap dua hari.",
    flowers: ["Spray Rose", "Sunflower", "Eucalyptus"],
  },
  {
    id: 8,
    shop: SHOPS[3],
    type: "bouquet",
    title: "Midnight Velvet",
    price: 900000,
    image: "/assets/bouquet/romance/midnight_velvet.png",
    category: "Warm",
    tag: "Romance",
    theme: "dark",
    isBestSeller: false,
    desc: "Romansa yang elegan dan misterius.",
    story: "Cinta yang dalam, gelap, dan memikat seperti malam.",
    care: "Simpan di tempat sejuk.",
    flowers: ["Red Rose"],
  },
  {
    id: 9,
    shop: SHOPS[1],
    type: "bouquet",
    title: "Peony Dream",
    price: 780000,
    image: "/assets/bouquet/romance/peony_dream.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Cinta lembut penuh harapan.",
    story: "Mewakili mimpi indah tentang cinta yang anggun.",
    care: "Ganti air secara rutin.",
    flowers: ["Pink Peony", "White Peony", "Baby's Breathe"],
  },
  {
    id: 10,
    shop: SHOPS[5],
    type: "bouquet",
    title: "Sweet Harmony",
    price: 760000,
    image: "/assets/bouquet/romance/sweet_harmony.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Keselarasan cinta yang hangat.",
    story: "Dua hati yang berjalan seirama dalam kesederhanaan.",
    care: "Hindari ruangan panas.",
    flowers: ["Pink Rose", "Ranunculus", "Eucalyptus"],
  },
  {
    id: 11,
    shop: SHOPS[4],
    type: "bouquet",
    title: "Autumn Blooms",
    price: 620000,
    image: "/assets/bouquet/gratitude/autumn_blooms.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Ungkapan terima kasih yang hangat.",
    story: "Seperti musim gugur, sederhana namun penuh makna.",
    care: "Ganti air setiap dua hari.",
    flowers: ["Spray Rose", "Sunflower", "Eucalyptus"],
  },
  {
    id: 12,
    shop: SHOPS[4],
    type: "bouquet",
    title: "Sol De Mi Vida",
    price: 650000,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Simbol rasa syukur dan penghargaan.",
    story: "Terinspirasi dari seseorang yang membawa cahaya dalam hidup.",
    care: "Letakkan di tempat terang.",
    flowers: ["Spray Rose", "Sunflower", "Solidago"],
  },
  {
    id: 13,
    shop: SHOPS[1],
    type: "bouquet",
    title: "Sunshine Bliss",
    price: 600000,
    image: "/assets/bouquet/gratitude/sunshine_bliss.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Keceriaan sederhana penuh kehangatan.",
    story: "Momen bahagia kecil yang layak dirayakan.",
    care: "Semprot ringan setiap pagi.",
    flowers: ["Yellow Tulip", "Lisianthus", "Spray Rose"],
  },
  { id: "promo-2", type: "promo" },
];
