// DATA TOKO (TENANTS)
export const SHOPS = [
  {
    id: 101,
    name: "Rosy Garden Bandung",
    location: "Dago, Bandung",
    image: "/assets/flowershop/rosy_garden.png",
    rating: 4.9,
    reviewCount: 1240,
    distance: "1.2 km",
    can_customize: true,
    openTime: "08.00 - 20.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 102,
    name: "Eternal Florist Jakarta",
    location: "Kemang, Jakarta Selatan",
    image: "/assets/flowershop/eternal_florist.png",
    rating: 4.7,
    reviewCount: 850,
    distance: "3.5 km",
    can_customize: false,
    openTime: "09.00 - 21.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 103,
    name: "The Flower Studio",
    location: "Cikini, Jakarta Pusat",
    image: "/assets/flowershop/the_flower_studio.png",
    rating: 4.8,
    reviewCount: 210,
    distance: "0.8 km",
    can_customize: true,
    openTime: "10.00 - 18.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 104,
    name: "Sentra Bunga Rawabelong",
    location: "Kebon Jeruk, Jakarta Barat",
    image: "/assets/flowershop/sentara_bunga.png",
    rating: 4.5,
    reviewCount: 5300,
    distance: "12 km",
    can_customize: false,
    openTime: "24 Jam",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 105,
    name: "Luxe De Pere En Fils",
    location: "SCBD, Jakarta Selatan",
    image: "/assets/flowershop/de_pere.png",
    rating: 5.0,
    reviewCount: 45,
    distance: "4.2 km",
    can_customize: true,
    openTime: "09.00 - 17.00",
    lat: -6.8869, lng: 107.6153,
  },
  {
    id: 106,
    name: "Petal & Paper",
    location: "BSD City, Tangerang",
    image: "/assets/flowershop/petal_paper.png",
    rating: 4.6,
    reviewCount: 112,
    distance: "25 km",
    can_customize: true,
    openTime: "08.00 - 20.00",
    lat: -6.8869, lng: 107.6153,
  },
];


const INITIAL_INVENTORY = [
  {
    id: "f-101",
    shopId: 101, 
    type: "flower",
    title: "Red Rose Premium",
    price: 15000,
    stock: 50,
    category: "romance",
    image: "https://images.unsplash.com/photo-1596073419667-9d77d59f033f?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "f-102",
    shopId: 101,
    type: "flower",
    title: "White Lily",
    price: 20000,
    stock: 30,
    category: "gratitude",
    image: "https://images.unsplash.com/photo-1572454591674-2739f30d8c40?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "p-101",
    shopId: 101,
    type: "packaging",
    packaging_type: "wrapping",
    title: "Premium Paper",
    price: 5000,
    stock: 100,
    colors: ["Pastel Pink", "Cream", "Black", "Transparan"] 
  },
  {
    id: "p-102",
    shopId: 101,
    type: "packaging",
    packaging_type: "ribbon",
    title: "Satin Ribbon",
    price: 2000,
    stock: 200,
    colors: ["Red", "Gold", "Silver"]
  }
];


export const allItems = [
  {
    id: 1,
    shop: SHOPS[0],
    type: "product",
    title: "Head Over Heels",
    price: 850000,
    stock: 0, 
    image: "/assets/bouquet/peace/crimson_promise.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    isBestSeller: true,
    desc: "Cinta yang meledak-ledak dan penuh afeksi.",
    story: "Terinspirasi dari kisah cinta klasik.",
    care: "Potong ujung batang 1cm setiap hari.",
    flowers: ["Mawar Merah (10)", "Baby Breath", "Daun Ruscus"],
  },
  {
    id: 2,
    shop: SHOPS[0],
    type: "product",
    title: "Sunset Harmony",
    price: 450000,
    stock: 12,
    image: "/assets/bouquet/peace/sunset_harmony.png",
    category: "Peace",
    tag: "Friendship",
    theme: "light",
    isBestSeller: false,
    desc: "Kesegaran pagi hari yang membawa ketenangan.",
    story: "Menyapa teman lama dengan kehangatan.",
    care: "Semprotkan air (mist) ke kelopak.",
    flowers: ["White Tulip (5)", "Lily of the Valley"],
  },
  {
    id: 8,
    shop: SHOPS[3],
    type: "product",
    title: "Midnight Velvet",
    price: 900000,
    stock: 0,
    image: "/assets/bouquet/romance/midnight_velvet.png",
    category: "Warm",
    tag: "Romance",
    theme: "dark",
    isBestSeller: false,
    desc: "Romansa yang elegan dan misterius.",
    story: "Cinta yang dalam, gelap, dan memikat.",
    care: "Simpan di tempat sejuk.",
    flowers: ["Red Rose Premium"],
  },
  {
    id: 3,
    shop: SHOPS[0],
    type: "product",
    title: "Bright Future",
    price: 450000,
    stock: 8,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    desc: "Masa depan cerah.",
    story: "Harapan baru.",
    care: "Ganti air.",
    flowers: ["Yellow Tulip"],
  },
  {
    id: 4,
    shop: SHOPS[5],
    type: "product",
    title: "Sweet Gratitude",
    price: 350000,
    stock: 15,
    image: "/assets/bouquet/peace/moonlight_serenity.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    desc: "Terima kasih tulus.",
    story: "Ungkapan syukur.",
    care: "Sejuk.",
    flowers: ["White Rose"],
  },
  {
    id: 5,
    shop: SHOPS[1],
    type: "product",
    title: "Silent Tears",
    price: 700000,
    stock: 3,
    image: "/assets/bouquet/regret/sweet_apology.png",
    category: "Gloomy",
    tag: "Grief",
    theme: "dark",
    desc: "Penghormatan terakhir.",
    story: "Kesedihan hening.",
    care: "Jauhkan matahari.",
    flowers: ["Dark Red Rose"],
  },
  { id: "promo-1", type: "promo" },
  {
    id: 6,
    shop: SHOPS[2],
    type: "product",
    title: "Midnight Regret",
    price: 480000,
    stock: 7,
    image: "/assets/bouquet/regret/first_date_bloom.png",
    category: "Gloomy",
    tag: "Regret",
    theme: "dark",
    desc: "Penyesalan dalam.",
    story: "Perasaan terlambat.",
    care: "Ganti air.",
    flowers: ["White Rose"],
  },
  {
    id: 7,
    shop: SHOPS[3],
    type: "product",
    title: "Garden Symphony",
    price: 820000,
    stock: 4,
    image: "/assets/bouquet/romance/garden_syphony.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    desc: "Harmoni cinta.",
    story: "Taman mekar.",
    care: "Potong batang.",
    flowers: ["Spray Rose"],
  },
  {
    id: 9,
    shop: SHOPS[1],
    type: "product",
    title: "Peony Dream",
    price: 780000,
    stock: 2,
    image: "/assets/bouquet/romance/peony_dream.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    desc: "Cinta lembut.",
    story: "Mimpi indah.",
    care: "Rutin ganti air.",
    flowers: ["Pink Peony"],
  },
  {
    id: 10,
    shop: SHOPS[5],
    type: "product",
    title: "Sweet Harmony",
    price: 760000,
    stock: 6,
    image: "/assets/bouquet/romance/sweet_harmony.png",
    category: "Warm",
    tag: "Romance",
    theme: "light",
    desc: "Keselarasan.",
    story: "Dua hati.",
    care: "Hindari panas.",
    flowers: ["Pink Rose"],
  },
  {
    id: 11,
    shop: SHOPS[4],
    type: "product",
    title: "Autumn Blooms",
    price: 620000,
    stock: 9,
    image: "/assets/bouquet/gratitude/autumn_blooms.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    desc: "Musim gugur.",
    story: "Sederhana.",
    care: "Ganti air.",
    flowers: ["Sunflower"],
  },
  {
    id: 12,
    shop: SHOPS[4],
    type: "product",
    title: "Sol De Mi Vida",
    price: 650000,
    stock: 11,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    desc: "Cahaya hidup.",
    story: "Penghargaan.",
    care: "Tempat terang.",
    flowers: ["Sunflower"],
  },
  {
    id: 13,
    shop: SHOPS[1],
    type: "product",
    title: "Sunshine Bliss",
    price: 600000,
    stock: 10,
    image: "/assets/bouquet/gratitude/sunshine_bliss.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    desc: "Keceriaan.",
    story: "Momen bahagia.",
    care: "Semprot.",
    flowers: ["Yellow Tulip"],
  },
  { id: "promo-2", type: "promo" },
];


