// DATA TOKO (TENANTS)
export const SHOPS = [
  {
    id: 101,
    name: "Rosy Garden Bandung",
    location: "Dago, Bandung",
    image: "/assets/flowershop/rosy_garden.png",
    rating: 4.9,
    reviewCount: 1240,
    distance: "1.2 km",
    can_customize: true,
    openTime: "08.00 - 20.00",
    lat: -6.8869,
    lng: 107.6153,
  },
  {
    id: 102,
    name: "Eternal Florist Jakarta",
    location: "Kemang, Jakarta Selatan",
    image: "/assets/flowershop/eternal_florist.png",
    rating: 4.7,
    reviewCount: 850,
    distance: "3.5 km",
    can_customize: false,
    openTime: "09.00 - 21.00",
    lat: -6.8869,
    lng: 107.6153,
  },
  {
    id: 103,
    name: "The Flower Studio",
    location: "Cikini, Jakarta Pusat",
    image: "/assets/flowershop/the_flower_studio.png",
    rating: 4.8,
    reviewCount: 210,
    distance: "0.8 km",
    can_customize: true,
    openTime: "10.00 - 18.00",
    lat: -6.8869,
    lng: 107.6153,
  },
  {
    id: 104,
    name: "Sentra Bunga Rawabelong",
    location: "Kebon Jeruk, Jakarta Barat",
    image: "/assets/flowershop/sentara_bunga.png",
    rating: 4.5,
    reviewCount: 5300,
    distance: "12 km",
    can_customize: false,
    openTime: "24 Jam",
    lat: -6.9175,
    lng: 107.6092,
  },
  {
    id: 105,
    name: "Luxe De Pere En Fils",
    location: "SCBD, Jakarta Selatan",
    image: "/assets/flowershop/de_pere.png",
    rating: 5.0,
    reviewCount: 45,
    distance: "4.2 km",
    can_customize: true,
    openTime: "09.00 - 17.00",
    lat: -6.8604,
    lng: 107.5977,
  },
  {
    id: 106,
    name: "Petal & Paper",
    location: "BSD City, Tangerang",
    image: "/assets/flowershop/petal_paper.png",
    rating: 4.6,
    reviewCount: 112,
    distance: "25 km",
    can_customize: true,
    openTime: "08.00 - 20.00",
    lat: -6.3014,
    lng: 106.6471,
  },
  {
    id: 107,
    name: "Rouvalis Flowers",
    location: "Kemang, Jakarta Selatan",
    image: "/assets/flowershop/rouvalis_flowers.jpg",
    rating: 4.8,
    reviewCount: 78,
    distance: "6.1 km",
    can_customize: true,
    openTime: "09.00 - 18.00",
    lat: -6.2782,
    lng: 106.8102,
  },
  {
    id: 108,
    name: "Petals Paradise",
    location: "Menteng, Jakarta Pusat",
    image: "/assets/flowershop/petals_paradise.png",
    rating: 4.7,
    reviewCount: 95,
    distance: "3.8 km",
    can_customize: false,
    openTime: "10.00 - 19.00",
    lat: -6.2016,
    lng: 106.8289,
  },
  {
    id: 109,
    name: "Flora House",
    location: "Tebet, Jakarta Selatan",
    image: "/assets/flowershop/flora_house.png",
    rating: 4.5,
    reviewCount: 60,
    distance: "5.0 km",
    can_customize: true,
    openTime: "08.30 - 17.30",
    lat: -6.2348,
    lng: 106.8388,
  },
  {
    id: 110,
    name: "Rose & Lily",
    location: "Cibubur, Jakarta Timur",
    image: "/assets/flowershop/rose_&_lily.png",
    rating: 4.9,
    reviewCount: 150,
    distance: "18 km",
    can_customize: true,
    openTime: "09.00 - 20.00",
    lat: -6.3585,
    lng: 106.8758,
  },
  {
    id: 111,
    name: "Gardenia Florist",
    location: "Pondok Indah, Jakarta Selatan",
    image: "/assets/flowershop/gardenia_florist.png",
    rating: 4.6,
    reviewCount: 80,
    distance: "7.5 km",
    can_customize: false,
    openTime: "07.30 - 18.00",
    lat: -6.2849,
    lng: 106.783,
  },
  {
    id: 112,
    name: "The Flower Loft",
    location: "Kelapa Gading, Jakarta Utara",
    image: "/assets/flowershop/the_flower_loft.png",
    rating: 4.8,
    reviewCount: 110,
    distance: "12 km",
    can_customize: true,
    openTime: "09.00 - 21.00",
    lat: -6.1495,
    lng: 106.9149,
  },
];

const INITIAL_INVENTORY = [
  {
    id: "f-101",
    shopId: 101,
    type: "flower",
    title: "Red Rose Premium",
    price: 15000,
    stock: 50,
    category: "romance",
    image:
      "https://images.unsplash.com/photo-1596073419667-9d77d59f033f?auto=format&fit=crop&q=80&w=300",
  },
  {
    id: "f-102",
    shopId: 101,
    type: "flower",
    title: "White Lily",
    price: 20000,
    stock: 30,
    category: "gratitude",
    image:
      "https://images.unsplash.com/photo-1572454591674-2739f30d8c40?auto=format&fit=crop&q=80&w=300",
  },
  {
    id: "p-101",
    shopId: 101,
    type: "packaging",
    packaging_type: "wrapping",
    title: "Premium Paper",
    price: 5000,
    stock: 100,
    colors: ["Pastel Pink", "Cream", "Black", "Transparan"],
  },
  {
    id: "p-102",
    shopId: 101,
    type: "packaging",
    packaging_type: "ribbon",
    title: "Satin Ribbon",
    price: 2000,
    stock: 200,
    colors: ["Red", "Gold", "Silver"],
  },
];

export const allItems = [
  {
    id: 1,
    shop: SHOPS[0],
    type: "product",
    title: "Head Over Heels",
    price: 850000,
    image: "/assets/bouquet/grief/crimson_promise.png",
    category: "Grief",
    tag: "Romance",
    theme: "light",
    isBestSeller: true,
    desc: "Cinta yang meledak-ledak dan penuh afeksi. Cocok untuk menyatakan perasaan yang mendalam.",
    story:
      "Terinspirasi dari kisah cinta klasik yang tak lekang oleh waktu. Merah melambangkan keberanian mencintai.",
    care: "Potong ujung batang 1cm setiap hari, ganti air dingin, dan jauhkan dari sinar matahari langsung.",
    flowers: [
      "Mawar Merah (Red Rose) - 10 tangkai",
      "Baby Breath - Filler",
      "Daun Ruscus - Greenery",
      "Pita Satin Premium Maroon",
    ],
    stock: 3,
  },
  {
    id: 2,
    shop: SHOPS[0],
    type: "product",
    title: "Sunset Harmony",
    price: 450000,
    image: "/assets/bouquet/grief/sunset_harmony.png",
    category: "Grief",
    tag: "Friendship",
    theme: "light",
    isBestSeller: false,
    desc: "Kesegaran pagi hari yang membawa ketenangan.",
    story:
      "Diciptakan untuk menyapa teman lama dengan kehangatan yang tidak berlebihan.",
    care: "Semprotkan air (mist) ke kelopak bunga tulip agar tetap segar.",
    flowers: [
      "White Tulip - 5 tangkai",
      "Lily of the Valley - 3 tangkai",
      "Transparent Wrapping",
    ],
  },
  { id: "promo-1", type: "promo" },
  {
    id: 3,
    shop: SHOPS[0],
    type: "product",
    title: "Bright Future",
    price: 450000,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Masa depan cerah yang penuh harapan.",
    story: "Melambangkan semangat baru dan rasa syukur atas perjalanan hidup.",
    care: "Ganti air setiap hari dan simpan di ruangan terang.",
    flowers: ["Yellow Tulip", "Seasonal filler flower"],
    stock: 5,
  },
  {
    id: 4,
    shop: SHOPS[5],
    type: "product",
    title: "Sweet Gratitude",
    price: 350000,
    image: "/assets/bouquet/grief/moonlight_serenity.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Ungkapan terima kasih yang sederhana dan tulus.",
    story:
      "Dirangkai untuk menyampaikan rasa syukur tanpa kata-kata berlebihan.",
    care: "Simpan di tempat sejuk dan ganti air secara berkala.",
    flowers: ["White Rose", "Soft wrapping paper"],
    stock: 9,
  },
  { id: "promo-1", type: "promo" },
  {
    id: 5,
    shop: SHOPS[1],
    type: "product",
    title: "Silent Tears",
    price: 700000,
    image: "/assets/bouquet/regret/sweet_apology.png",
    category: "Grief",
    tag: "Grief",
    theme: "dark",
    isBestSeller: false,
    desc: "Penghormatan terakhir dalam keheningan.",
    story:
      "Dirancang untuk menyampaikan duka cita dengan cara yang elegan dan penuh empati.",
    care: "Jauhkan dari matahari langsung dan panas berlebih.",
    flowers: ["Dark Red Rose", "Black wrapping"],
    stock: 2,
  },
  {
    id: 6,
    shop: SHOPS[2],
    type: "product",
    title: "Midnight Regret",
    price: 480000,
    image: "/assets/bouquet/regret/first_date_bloom.png",
    category: "Regret",
    tag: "Regret",
    theme: "dark",
    isBestSeller: false,
    desc: "Penyesalan dalam.",
    story: "Perasaan terlambat.",
    care: "Ganti air.",
    flowers: ["White Rose"],
    stock: 11,
  },
  {
    id: 7,
    shop: SHOPS[3],
    type: "product",
    title: "Garden Symphony",
    price: 820000,
    image: "/assets/bouquet/romance/garden_syphony.png",
    category: "Romance",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Harmoni cinta.",
    story: "Taman mekar.",
    care: "Potong batang.",
    flowers: ["Spray Rose"],
    stock: 6,
  },
  {
    id: 8,
    shop: SHOPS[9],
    type: "product",
    title: "Midnight Velvet",
    price: 900000,
    image: "/assets/bouquet/romance/midnight_velvet.png",
    category: "Romance",
    tag: "Romance",
    theme: "dark",
    isBestSeller: false,
    desc: "Romansa yang elegan dan misterius.",
    story: "Cinta yang dalam, gelap, dan memikat.",
    care: "Simpan di tempat sejuk.",
    flowers: ["Red Rose Premium"],
    stock: 14,
  },
  {
    id: 9,
    shop: SHOPS[6],
    type: "product",
    title: "Peony Dream",
    price: 780000,
    image: "/assets/bouquet/romance/peony_dream.png",
    category: "Romance",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Cinta lembut.",
    story: "Mimpi indah.",
    care: "Rutin ganti air.",
    flowers: ["Pink Peony"],
    stock: 5,
  },
  {
    id: 10,
    shop: SHOPS[5],
    type: "product",
    title: "Sweet Harmony",
    price: 760000,
    image: "/assets/bouquet/romance/sweet_harmony.png",
    category: "Romance",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Keselarasan.",
    story: "Dua hati.",
    care: "Hindari panas.",
    flowers: ["Pink Rose"],
    stock: 2,
  },
  {
    id: 11,
    shop: SHOPS[4],
    type: "product",
    title: "Autumn Blooms",
    price: 620000,
    image: "/assets/bouquet/gratitude/autumn_blooms.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Musim gugur yang hangat dan menenangkan.",
    story: "Kesederhanaan yang membawa rasa syukur.",
    care: "Ganti air secara rutin.",
    flowers: ["Sunflower"],
    stock: 9,
  },
  {
    id: 12,
    shop: SHOPS[4],
    type: "product",
    title: "Sol De Mi Vida",
    price: 650000,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Cahaya hidup yang penuh arti.",
    story: "Ungkapan penghargaan yang tulus.",
    care: "Tempatkan di area terang.",
    flowers: ["Sunflower"],
    stock: 0,
  },
  {
    id: 13,
    shop: SHOPS[1],
    type: "product",
    title: "Sunshine Bliss",
    price: 600000,
    image: "/assets/bouquet/gratitude/sunshine_bliss.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Keceriaan yang sederhana.",
    story: "Momen bahagia yang hangat.",
    care: "Semprot ringan pada kelopak.",
    flowers: ["Yellow Tulip"],
    stock: 4,
  },
  {
    id: 14,
    shop: SHOPS[0],
    type: "product",
    title: "Romantic Evening",
    price: 750000,
    image: "/assets/bouquet/romance/romantic_evening.png",
    category: "Romance",
    tag: "Love",
    theme: "light",
    isBestSeller: false,
    desc: "Romansa lembut untuk momen spesial.",
    story: "Diciptakan untuk pasangan tercinta.",
    care: "Jauhkan dari sinar matahari langsung.",
    flowers: ["Red Rose", "White Lily"],
    stock: 2,
  },
  {
    id: 15,
    shop: SHOPS[7],
    type: "product",
    title: "Regretful Goodbye",
    price: 500000,
    image: "/assets/bouquet/regret/regretful_goodbye.png",
    category: "Regret",
    tag: "Farewell",
    theme: "dark",
    isBestSeller: false,
    desc: "Perpisahan penuh penyesalan.",
    story: "Momen mengingat yang telah berlalu.",
    care: "Hindari panas berlebih.",
    flowers: ["Blue Orchid"],
    stock: 6,
  },
  {
    id: 16,
    shop: SHOPS[3],
    type: "product",
    title: "Grief & Grace",
    price: 650000,
    image: "/assets/bouquet/grief/grief_and_grace.png",
    category: "Grief",
    tag: "Condolence",
    theme: "dark",
    isBestSeller: false,
    desc: "Kesedihan yang tetap anggun.",
    story: "Ungkapan duka cita yang penuh hormat.",
    care: "Semprot ringan secara berkala.",
    flowers: ["White Rose", "Baby's Breath"],
    stock: 5,
  },
  {
    id: 17,
    shop: SHOPS[4],
    type: "product",
    title: "Warm Embrace",
    price: 700000,
    image: "/assets/bouquet/gratitude/warm_embrace.png",
    category: "Gratitude",
    tag: "Thank You",
    theme: "light",
    isBestSeller: false,
    desc: "Pelukan hangat dalam rangkaian bunga.",
    story: "Untuk sahabat tercinta.",
    care: "Jaga kelembaban bunga.",
    flowers: ["Pink Carnation", "Yellow Tulip"],
    stock: 6,
  },
  {
    id: 18,
    shop: SHOPS[5],
    type: "product",
    title: "Midnight Mourning",
    price: 800000,
    image: "/assets/bouquet/grief/midnight_mourning.png",
    category: "Grief",
    tag: "Sympathy",
    theme: "dark",
    isBestSeller: true,
    desc: "Kesedihan yang mendalam di malam hari.",
    story: "Untuk momen duka yang sunyi.",
    care: "Hindari angin kencang.",
    flowers: ["Black Orchid", "White Lily"],
    stock: 8,
  },
  { id: "promo-2", type: "promo" },
  {
    id: 19,
    shop: SHOPS[6],
    type: "product",
    title: "Loving Whisper",
    price: 720000,
    image: "/assets/bouquet/romance/loving_whisper.png",
    category: "Romance",
    tag: "Love",
    theme: "light",
    isBestSeller: true,
    desc: "Bisikan cinta yang lembut.",
    story: "Untuk pasangan tercinta.",
    care: "Jauhkan dari panas.",
    flowers: ["Red Rose", "Pink Peony"],
    stock: 4,
  },
  {
    id: 20,
    shop: SHOPS[7],
    type: "product",
    title: "Fading Memories",
    price: 550000,
    image: "/assets/bouquet/regret/fading_memories.png",
    category: "Regret",
    tag: "Remembrance",
    theme: "dark",
    isBestSeller: true,
    desc: "Kenangan yang perlahan memudar.",
    story: "Mengiringi ingatan masa lalu.",
    care: "Simpan di tempat sejuk.",
    flowers: ["Lavender", "White Lily"],
    stock: 1,
  },
  {
    id: 21,
    shop: SHOPS[2],
    type: "product",
    title: "Head Over Heels",
    price: 850000,
    image: "/assets/bouquet/grief/crimson_promise.png",
    category: "Grief",
    tag: "Romance",
    theme: "light",
    isBestSeller: true,
    desc: "Cinta yang meledak-ledak dan penuh afeksi. Cocok untuk menyatakan perasaan yang mendalam.",
    story:
      "Terinspirasi dari kisah cinta klasik yang tak lekang oleh waktu. Merah melambangkan keberanian mencintai.",
    care: "Potong ujung batang 1cm setiap hari, ganti air dingin, dan jauhkan dari sinar matahari langsung.",
    flowers: [
      "Mawar Merah (Red Rose) - 10 tangkai",
      "Baby Breath - Filler",
      "Daun Ruscus - Greenery",
      "Pita Satin Premium Maroon",
    ],
    stock: 3,
  },
  {
    id: 22,
    shop: SHOPS[11],
    type: "product",
    title: "Sunset Harmony",
    price: 450000,
    image: "/assets/bouquet/grief/sunset_harmony.png",
    category: "Grief",
    tag: "Friendship",
    theme: "light",
    isBestSeller: false,
    desc: "Kesegaran pagi hari yang membawa ketenangan.",
    story:
      "Diciptakan untuk menyapa teman lama dengan kehangatan yang tidak berlebihan.",
    care: "Semprotkan air (mist) ke kelopak bunga tulip agar tetap segar.",
    flowers: [
      "White Tulip - 5 tangkai",
      "Lily of the Valley - 3 tangkai",
      "Transparent Wrapping",
    ],
    stock: 1,
  },
  {
    id: 23,
    shop: SHOPS[2],
    type: "product",
    title: "Bright Future",
    price: 450000,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Masa depan cerah yang penuh harapan.",
    story: "Melambangkan semangat baru dan rasa syukur atas perjalanan hidup.",
    care: "Ganti air setiap hari dan simpan di ruangan terang.",
    flowers: ["Yellow Tulip", "Seasonal filler flower"],
    stock: 2,
  },
  {
    id: 24,
    shop: SHOPS[11],
    type: "product",
    title: "Sweet Gratitude",
    price: 350000,
    image: "/assets/bouquet/grief/moonlight_serenity.png",
    category: "Warm",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Ungkapan terima kasih yang sederhana dan tulus.",
    story:
      "Dirangkai untuk menyampaikan rasa syukur tanpa kata-kata berlebihan.",
    care: "Simpan di tempat sejuk dan ganti air secara berkala.",
    flowers: ["White Rose", "Soft wrapping paper"],
    stock: 6,
  },
  { id: "promo-2", type: "promo" },
  {
    id: 25,
    shop: SHOPS[10],
    type: "product",
    title: "Silent Tears",
    price: 700000,
    image: "/assets/bouquet/regret/sweet_apology.png",
    category: "Grief",
    tag: "Grief",
    theme: "dark",
    isBestSeller: false,
    desc: "Penghormatan terakhir dalam keheningan.",
    story:
      "Dirancang untuk menyampaikan duka cita dengan cara yang elegan dan penuh empati.",
    care: "Jauhkan dari matahari langsung dan panas berlebih.",
    flowers: ["Dark Red Rose", "Black wrapping"],
    stock: 9,
  },
  {
    id: 26,
    shop: SHOPS[8],
    type: "product",
    title: "Midnight Regret",
    price: 480000,
    image: "/assets/bouquet/regret/first_date_bloom.png",
    category: "Regret",
    tag: "Regret",
    theme: "dark",
    isBestSeller: false,
    desc: "Penyesalan dalam.",
    story: "Perasaan terlambat.",
    care: "Ganti air.",
    flowers: ["White Rose"],
    stock: 4,
  },
  {
    id: 27,
    shop: SHOPS[9],
    type: "product",
    title: "Garden Symphony",
    price: 820000,
    image: "/assets/bouquet/romance/garden_syphony.png",
    category: "Romance",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Harmoni cinta.",
    story: "Taman mekar.",
    care: "Potong batang.",
    flowers: ["Spray Rose"],
    stock: 7,
  },
  {
    id: 28,
    shop: SHOPS[9],
    type: "product",
    title: "Midnight Velvet",
    price: 900000,
    image: "/assets/bouquet/romance/midnight_velvet.png",
    category: "Romance",
    tag: "Romance",
    theme: "dark",
    isBestSeller: false,
    desc: "Romansa yang elegan dan misterius.",
    story: "Cinta yang dalam, gelap, dan memikat.",
    care: "Simpan di tempat sejuk.",
    flowers: ["Red Rose Premium"],
    stock: 5,
  },
  {
    id: 29,
    shop: SHOPS[4],
    type: "product",
    title: "Peony Dream",
    price: 780000,
    image: "/assets/bouquet/romance/peony_dream.png",
    category: "Romance",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Cinta lembut.",
    story: "Mimpi indah.",
    care: "Rutin ganti air.",
    flowers: ["Pink Peony"],
    stock: 3,
  },
  {
    id: 30,
    shop: SHOPS[6],
    type: "product",
    title: "Sweet Harmony",
    price: 760000,
    image: "/assets/bouquet/romance/sweet_harmony.png",
    category: "Romance",
    tag: "Romance",
    theme: "light",
    isBestSeller: false,
    desc: "Keselarasan.",
    story: "Dua hati.",
    care: "Hindari panas.",
    flowers: ["Pink Rose"],
    stock: 3,
  },
  {
    id: 31,
    shop: SHOPS[6],
    type: "product",
    title: "Autumn Blooms",
    price: 620000,
    image: "/assets/bouquet/gratitude/autumn_blooms.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Musim gugur yang hangat dan menenangkan.",
    story: "Kesederhanaan yang membawa rasa syukur.",
    care: "Ganti air secara rutin.",
    flowers: ["Sunflower"],
    stock: 3,
  },
  {
    id: 32,
    shop: SHOPS[8],
    type: "product",
    title: "Sol De Mi Vida",
    price: 650000,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Cahaya hidup yang penuh arti.",
    story: "Ungkapan penghargaan yang tulus.",
    care: "Tempatkan di area terang.",
    flowers: ["Sunflower"],
    stock: 3,
  },
  {
    id: 33,
    shop: SHOPS[6],
    type: "product",
    title: "Sunshine Bliss",
    price: 600000,
    image: "/assets/bouquet/gratitude/sunshine_bliss.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Keceriaan yang sederhana.",
    story: "Momen bahagia yang hangat.",
    care: "Semprot ringan pada kelopak.",
    flowers: ["Yellow Tulip"],
    stock: 3,
  },
  {
    id: 34,
    shop: SHOPS[9],
    type: "product",
    title: "Romantic Evening",
    price: 750000,
    image: "/assets/bouquet/romance/romantic_evening.png",
    category: "Romance",
    tag: "Love",
    theme: "light",
    isBestSeller: false,
    desc: "Romansa lembut untuk momen spesial.",
    story: "Diciptakan untuk pasangan tercinta.",
    care: "Jauhkan dari sinar matahari langsung.",
    flowers: ["Red Rose", "White Lily"],
    stock: 3,
  },
  {
    id: 35,
    shop: SHOPS[11],
    type: "product",
    title: "Regretful Goodbye",
    price: 500000,
    image: "/assets/bouquet/regret/regretful_goodbye.png",
    category: "Regret",
    tag: "Farewell",
    theme: "dark",
    isBestSeller: false,
    desc: "Perpisahan penuh penyesalan.",
    story: "Momen mengingat yang telah berlalu.",
    care: "Hindari panas berlebih.",
    flowers: ["Blue Orchid"],
    stock: 3,
  },
  {
    id: 36,
    shop: SHOPS[3],
    type: "product",
    title: "Grief & Grace",
    price: 650000,
    image: "/assets/bouquet/grief/grief_and_grace.png",
    category: "Grief",
    tag: "Condolence",
    theme: "dark",
    isBestSeller: false,
    desc: "Kesedihan yang tetap anggun.",
    story: "Ungkapan duka cita yang penuh hormat.",
    care: "Semprot ringan secara berkala.",
    flowers: ["White Rose", "Baby's Breath"],
    stock: 3,
  },
  {
    id: 37,
    shop: SHOPS[2],
    type: "product",
    title: "Warm Embrace",
    price: 700000,
    image: "/assets/bouquet/gratitude/warm_embrace.png",
    category: "Gratitude",
    tag: "Thank You",
    theme: "light",
    isBestSeller: false,
    desc: "Pelukan hangat dalam rangkaian bunga.",
    story: "Untuk sahabat tercinta.",
    care: "Jaga kelembaban bunga.",
    flowers: ["Pink Carnation", "Yellow Tulip"],
    stock: 3,
  },
  { id: "promo-3", type: "promo" },
  {
    id: 38,
    shop: SHOPS[9],
    type: "product",
    title: "Midnight Mourning",
    price: 800000,
    image: "/assets/bouquet/grief/midnight_mourning.png",
    category: "Grief",
    tag: "Sympathy",
    theme: "dark",
    isBestSeller: true,
    desc: "Kesedihan yang mendalam di malam hari.",
    story: "Untuk momen duka yang sunyi.",
    care: "Hindari angin kencang.",
    flowers: ["Black Orchid", "White Lily"],
    stock: 3,
  },
  {
    id: 39,
    shop: SHOPS[11],
    type: "product",
    title: "Loving Whisper",
    price: 720000,
    image: "/assets/bouquet/romance/loving_whisper.png",
    category: "Romance",
    tag: "Love",
    theme: "light",
    isBestSeller: true,
    desc: "Bisikan cinta yang lembut.",
    story: "Untuk pasangan tercinta.",
    care: "Jauhkan dari panas.",
    flowers: ["Red Rose", "Pink Peony"],
    stock: 3,
  },
  {
    id: 40,
    shop: SHOPS[11],
    type: "product",
    title: "Fading Memories",
    price: 550000,
    image: "/assets/bouquet/regret/fading_memories.png",
    category: "Regret",
    tag: "Remembrance",
    theme: "dark",
    isBestSeller: true,
    desc: "Kenangan yang perlahan memudar.",
    story: "Mengiringi ingatan masa lalu.",
    care: "Simpan di tempat sejuk.",
    flowers: ["Lavender", "White Lily"],
    stock: 3,
  },
  {
    id: 41,
    shop: SHOPS[0],
    type: "product",
    title: "Autumn Blooms",
    price: 620000,
    image: "/assets/bouquet/gratitude/autumn_blooms.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Musim gugur yang hangat dan menenangkan.",
    story: "Kesederhanaan yang membawa rasa syukur.",
    care: "Ganti air secara rutin.",
    flowers: ["Sunflower"],
    stock: 3,
  },
  {
    id: 42,
    shop: SHOPS[1],
    type: "product",
    title: "Sol De Mi Vida",
    price: 650000,
    image: "/assets/bouquet/gratitude/sol_de_mi_vida.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Cahaya hidup yang penuh arti.",
    story: "Ungkapan penghargaan yang tulus.",
    care: "Tempatkan di area terang.",
    flowers: ["Sunflower"],
    stock: 3,
  },
  {
    id: 43,
    shop: SHOPS[10],
    type: "product",
    title: "Sunshine Bliss",
    price: 600000,
    image: "/assets/bouquet/gratitude/sunshine_bliss.png",
    category: "Gratitude",
    tag: "Gratitude",
    theme: "light",
    isBestSeller: false,
    desc: "Keceriaan yang sederhana.",
    story: "Momen bahagia yang hangat.",
    care: "Semprot ringan pada kelopak.",
    flowers: ["Yellow Tulip"],
    stock: 3,
  },
  { id: "promo-1", type: "promo" },
  {
    id: 44,
    shop: SHOPS[1],
    type: "product",
    title: "Romantic Evening",
    price: 750000,
    image: "/assets/bouquet/romance/romantic_evening.png",
    category: "Romance",
    tag: "Love",
    theme: "light",
    isBestSeller: false,
    desc: "Romansa lembut untuk momen spesial.",
    story: "Diciptakan untuk pasangan tercinta.",
    care: "Jauhkan dari sinar matahari langsung.",
    flowers: ["Red Rose", "White Lily"],
    stock: 3,
  },
  {
    id: 45,
    shop: SHOPS[8],
    type: "product",
    title: "Regretful Goodbye",
    price: 500000,
    image: "/assets/bouquet/regret/regretful_goodbye.png",
    category: "Regret",
    tag: "Farewell",
    theme: "dark",
    isBestSeller: false,
    desc: "Perpisahan penuh penyesalan.",
    story: "Momen mengingat yang telah berlalu.",
    care: "Hindari panas berlebih.",
    flowers: ["Blue Orchid"],
    stock: 3,
  },
  {
    id: 46,
    shop: SHOPS[10],
    type: "product",
    title: "Grief & Grace",
    price: 650000,
    image: "/assets/bouquet/grief/grief_and_grace.png",
    category: "Grief",
    tag: "Condolence",
    theme: "dark",
    isBestSeller: false,
    desc: "Kesedihan yang tetap anggun.",
    story: "Ungkapan duka cita yang penuh hormat.",
    care: "Semprot ringan secara berkala.",
    flowers: ["White Rose", "Baby's Breath"],
    stock: 3,
  },
  {
    id: 47,
    shop: SHOPS[10],
    type: "product",
    title: "Warm Embrace",
    price: 700000,
    image: "/assets/bouquet/gratitude/warm_embrace.png",
    category: "Gratitude",
    tag: "Thank You",
    theme: "light",
    isBestSeller: false,
    desc: "Pelukan hangat dalam rangkaian bunga.",
    story: "Untuk sahabat tercinta.",
    care: "Jaga kelembaban bunga.",
    flowers: ["Pink Carnation", "Yellow Tulip"],
    stock: 3,
  },
  {
    id: 48,
    shop: SHOPS[10],
    type: "product",
    title: "Midnight Mourning",
    price: 800000,
    image: "/assets/bouquet/grief/midnight_mourning.png",
    category: "Grief",
    tag: "Sympathy",
    theme: "dark",
    isBestSeller: true,
    desc: "Kesedihan yang mendalam di malam hari.",
    story: "Untuk momen duka yang sunyi.",
    care: "Hindari angin kencang.",
    flowers: ["Black Orchid", "White Lily"],
    stock: 3,
  },
  {
    id: 49,
    shop: SHOPS[7],
    type: "product",
    title: "Loving Whisper",
    price: 720000,
    image: "/assets/bouquet/romance/loving_whisper.png",
    category: "Romance",
    tag: "Love",
    theme: "light",
    isBestSeller: true,
    desc: "Bisikan cinta yang lembut.",
    story: "Untuk pasangan tercinta.",
    care: "Jauhkan dari panas.",
    flowers: ["Red Rose", "Pink Peony"],
    stock: 3,
  },
  { id: "promo-4", type: "promo" },
  {
    id: 50,
    shop: SHOPS[8],
    type: "product",
    title: "Fading Memories",
    price: 550000,
    image: "/assets/bouquet/regret/fading_memories.png",
    category: "Regret",
    tag: "Remembrance",
    theme: "dark",
    isBestSeller: true,
    desc: "Kenangan yang perlahan memudar.",
    story: "Mengiringi ingatan masa lalu.",
    care: "Simpan di tempat sejuk.",
    flowers: ["Lavender", "White Lily"],
    stock: 3,
  },
];
